# Generated by Django 3.0.5 on 2020-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_remove_conferenceinfo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceinfo',
            name='year',
            field=models.IntegerField(default=2000, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='conference_name',
            field=models.CharField(max_length=50),
        ),
    ]
