# Generated by Django 2.0.6 on 2020-05-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20200511_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceinfo',
            options={'verbose_name': '会议信息', 'verbose_name_plural': '会议信息'},
        ),
        migrations.AlterModelOptions(
            name='paperinfo',
            options={'verbose_name': '论文信息', 'verbose_name_plural': '论文信息'},
        ),
        migrations.RemoveField(
            model_name='paperinfo',
            name='conference_name',
        ),
        migrations.RemoveField(
            model_name='paperinfo',
            name='year',
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.ConferenceInfo'),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='affiliations',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='read_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
