# Generated by Django 3.1.4 on 2021-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmstring',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
