# Generated by Django 3.1.1 on 2020-10-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='aliasname',
        ),
    ]
