# Generated by Django 3.1.2 on 2020-10-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20201010_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmString',
        ),
    ]
