# Generated by Django 3.1.2 on 2020-10-11 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_delete_confirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1918ab8a-0b7d-11eb-b0dd-d481d7a96759'), max_length=36),
        ),
    ]
