# Generated by Django 3.1.2 on 2020-10-13 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_userinformation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('940cb340-0d4e-11eb-a0e7-d481d7a96759'), max_length=36),
        ),
    ]
