# Generated by Django 3.1.2 on 2020-10-20 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20201013_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='unread_message',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('795f02e6-1285-11eb-8bdc-d481d7a96759'), max_length=36),
        ),
    ]
