# Generated by Django 3.1.2 on 2020-10-20 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_auto_20201020_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b92b4af0-1286-11eb-9e64-d481d7a96759'), max_length=36),
        ),
    ]
