# Generated by Django 3.1.2 on 2020-10-21 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20200512_1411'),
        ('userinfo', '0008_auto_20201020_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('880415e6-139f-11eb-8354-d481d7a96759'), max_length=36),
        ),
        migrations.CreateModel(
            name='PaperViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_times', models.IntegerField(default=1)),
                ('view_time', models.DateTimeField(auto_now_add=True)),
                ('already_deleted', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paperinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '论文浏览记录',
                'verbose_name_plural': '论文浏览记录',
                'ordering': ['-view_time'],
            },
        ),
    ]
