# Generated by Django 3.1.2 on 2021-03-09 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0012_auto_20210225_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('23e1e480-80dc-11eb-a4bf-acde48001122'), max_length=36),
        ),
    ]
