# Generated by Django 3.1.2 on 2021-03-11 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0012_auto_20210225_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a03bf0f8-8227-11eb-adb1-509a4ccbe93b'), max_length=36),
        ),
    ]
