# Generated by Django 3.1.7 on 2021-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0013_auto_20210309_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
