# Generated by Django 3.1.2 on 2021-03-11 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0013_auto_20210311_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ba8eb18c-8227-11eb-9a83-509a4ccbe93b'), max_length=36),
        ),
    ]
